export type GameCatalogItem = {
  number: string;
  slug: string;
  title: string;
  english: string;
  description: string;
  image: string;
  tags: string[];
  kind: "街机" | "棋牌" | "动作" | "射击" | "益智" | "社交" | "竞速" | "联机" | "策略" | "放置";
  className: string;
};

export const games: GameCatalogItem[] = [
  {
    number: "01",
    slug: "gold-miner",
    title: "黄金矿工",
    english: "GOLD RUSH",
    description: "看准时机放下抓钩，在岩层深处寻找金块与钻石。",
    image: "/gold-miner.webp",
    tags: ["街机", "单人", "50 秒"],
    kind: "街机",
    className: "gold-game",
  },
  {
    number: "02",
    slug: "doudizhu",
    title: "斗地主",
    english: "LANDLORD",
    description: "抢地主、组牌、压制，与两位电脑牌手打完一局。",
    image: "/doudizhu.webp",
    tags: ["棋牌", "三人", "策略"],
    kind: "棋牌",
    className: "card-game",
  },
  {
    number: "03",
    slug: "bubble-battle",
    title: "泡泡堂",
    english: "BUBBLE BATTLE",
    description: "单人清场、本地对战或创建在线房间，用连锁水花封锁路线并击败对手。",
    image: "/bubble-battle.webp",
    tags: ["动作", "双人", "在线房间"],
    kind: "动作",
    className: "bubble-game",
  },
  {
    number: "04",
    slug: "police-chase",
    title: "夜巡追捕",
    english: "NIGHT PATROL",
    description: "摆动准星、发射手铐，在倒计时结束前抓住小偷并追回证物。",
    image: "/police-chase.png",
    tags: ["街机", "单人", "连击追捕"],
    kind: "射击",
    className: "police-game",
  },
  {
    number: "05",
    slug: "critical-operation",
    title: "临界行动",
    english: "CRITICAL OPERATION",
    description: "突入港口仓库，以第一人称视角清除敌方机器人，并在倒计时结束前拆除装置。",
    image: "/critical-operation.svg",
    tags: ["第一人称", "战术射击", "拆弹"],
    kind: "射击",
    className: "tactical-game",
  },
  {
    number: "06",
    slug: "tetris-game",
    title: "AI 俄罗斯方块",
    english: "STACK LAB",
    description: "手动完成经典堆叠，或交给两步前瞻 AI，并实时观察它选择旋转与落点。",
    image: "/tetris-game.webp",
    tags: ["益智", "单人", "AI 自动"],
    kind: "益智",
    className: "tetris-game",
  },
  {
    number: "07",
    slug: "anonymous-chat",
    title: "匿名夜话",
    english: "MIDNIGHT FREQUENCY",
    description:
      "无需账号，带着随机代号进入局域网频道，围绕今晚的话题交换回应与共鸣。",
    image: "/anonymous-chat.svg",
    tags: ["社交", "局域网", "匿名"],
    kind: "社交",
    className: "chat-game",
  },
  {
    number: "08",
    slug: "pacman",
    title: "吃豆人",
    english: "PAC-MAN",
    description: "穿过霓虹迷宫吃完豆子，利用能量豆反击幽灵，并挑战连续十二关。",
    image: "/pacman.svg",
    tags: ["街机", "单人", "迷宫"],
    kind: "街机",
    className: "pacman-game",
  },
  {
    number: "09",
    slug: "connect-four",
    title: "四子棋",
    english: "CONNECT FOUR",
    description: "把棋子投入七列棋盘，率先横向、纵向或斜向连成四子；支持人机和本地双人。",
    image: "/connect-four.svg",
    tags: ["棋类", "人机", "双人"],
    kind: "棋牌",
    className: "connect-four-game",
  },
  {
    number: "10",
    slug: "2048",
    title: "2048",
    english: "NUMBER MERGE",
    description: "滑动数字方块，让相同数字相遇合并，在棋盘被填满之前抵达 2048。",
    image: "/2048.svg",
    tags: ["益智", "单人", "数字"],
    kind: "益智",
    className: "number-game",
  },
  {
    number: "11",
    slug: "asteroids",
    title: "小行星",
    english: "ASTEROIDS",
    description: "驾驶矢量飞船穿越陨石带，旋转、推进并射击，在碎石围攻中刷新得分。",
    image: "/asteroids.svg",
    tags: ["街机", "射击", "复古"],
    kind: "射击",
    className: "asteroids-game",
  },
  {
    number: "12",
    slug: "hexgl",
    title: "极速光轨",
    english: "HEXGL",
    description: "进入 WebGL 未来都市赛道，用键盘或触控驾驶反重力赛车冲击最快圈速。",
    image: "/hexgl.svg",
    tags: ["竞速", "3D", "WebGL"],
    kind: "竞速",
    className: "hexgl-game",
  },
  {
    number: "13",
    slug: "hextris",
    title: "六角拼图",
    english: "HEXTRIS",
    description: "旋转六角核心接住彩色方块，让同色边连续消除，在加速坠落中维持节奏。",
    image: "/hextris.svg",
    tags: ["益智", "反应", "触控"],
    kind: "益智",
    className: "hextris-game",
  },
  {
    number: "14",
    slug: "tosios",
    title: "地牢枪手",
    english: "TOSIOS",
    description: "创建本地房间，与同一局域网的队友进入像素地牢，闪避怪物并争夺排行榜。",
    image: "/tosios.svg",
    tags: ["联机", "射击", "局域网"],
    kind: "联机",
    className: "tosios-game",
  },
  {
    number: "15",
    slug: "armor-alley",
    title: "装甲峡谷",
    english: "ARMOR ALLEY",
    description: "驾驶直升机掩护地面车队，购买单位、占领碉堡，在经典横向战场上推进前线。",
    image: "/armor-alley.svg",
    tags: ["策略", "动作", "战役"],
    kind: "策略",
    className: "armor-game",
  },
  {
    number: "16",
    slug: "trigger-rally",
    title: "尘土拉力",
    english: "TRIGGER RALLY",
    description: "驶入开放山地赛段，在沙土、坡道与连续弯角之间挑战个人最快纪录。",
    image: "/trigger-rally.jpg",
    tags: ["竞速", "3D", "离线存档"],
    kind: "竞速",
    className: "trigger-rally-game",
  },
  {
    number: "17",
    slug: "micro-racing",
    title: "微型赛车",
    english: "MICRO RACING",
    description: "俯瞰低多边形赛道，创建房间、加入电脑车手，在实时物理竞速中冲线。",
    image: "/micro-racing.png",
    tags: ["竞速", "人机", "实时房间"],
    kind: "竞速",
    className: "micro-racing-game",
  },
  {
    number: "18",
    slug: "racez",
    title: "霓虹赛车",
    english: "RACEZ.IO",
    description: "选择车色和森林或雪地赛道，驾驶低多边形赛车完成检查点与圈速挑战。",
    image: "/racez.png",
    tags: ["竞速", "3D", "单人练习"],
    kind: "竞速",
    className: "racez-game",
  },
  {
    number: "19",
    slug: "javascript-racer",
    title: "公路追风",
    english: "JAVASCRIPT RACER",
    description: "用方向键驶上复古伪 3D 公路，在车流、山丘和弯道中刷新最快圈速。",
    image: "/javascript-racer.png",
    tags: ["竞速", "复古", "Canvas"],
    kind: "竞速",
    className: "javascript-racer-game",
  },
  {
    number: "20",
    slug: "solitairey",
    title: "百变接龙",
    english: "SOLITAIREY",
    description: "在同一张绿绒牌桌上切换空当接龙、蜘蛛纸牌、金字塔与经典接龙等十六种玩法。",
    image: "/solitairey.jpg",
    tags: ["棋牌", "16 种玩法", "单人"],
    kind: "棋牌",
    className: "solitaire-game",
  },
  {
    number: "21",
    slug: "js-solitaire",
    title: "经典纸牌",
    english: "KLONDIKE",
    description: "复刻经典桌面纸牌，用点击或拖拽整理红黑相间的牌列，把四种花色依次送入基座。",
    image: "/js-solitaire.png",
    tags: ["棋牌", "接龙", "复古"],
    kind: "棋牌",
    className: "classic-solitaire-game",
  },
  {
    number: "22",
    slug: "blackjack",
    title: "经典二十一点",
    english: "BLACKJACK",
    description: "观察起手牌，在要牌与停牌之间权衡风险，争取比庄家更接近二十一点而不爆牌。",
    image: "/blackjack.png",
    tags: ["棋牌", "人机", "概率"],
    kind: "棋牌",
    className: "blackjack-game",
  },
  {
    number: "23",
    slug: "multiplayer-blackjack",
    title: "联机二十一点",
    english: "BLACKJACK ROOMS",
    description: "创建房间并分享房间号，与同一局域网里的朋友轮流要牌、停牌并比较本局最佳手牌。",
    image: "/multiplayer-blackjack.png",
    tags: ["棋牌", "局域网", "多人"],
    kind: "联机",
    className: "multiplayer-blackjack-game",
  },
  {
    number: "24",
    slug: "starport-salvage-idle",
    title: "星港拾荒局",
    english: "STARPORT SALVAGE",
    description: "点击打捞残骸，调度无人机与熔炉，把废金属变成合金并完成订单，离线时星港也会持续运转。",
    image: "/starport-salvage-idle.svg",
    tags: ["放置", "经营", "离线收益"],
    kind: "放置",
    className: "starport-idle-game",
  },
];

export function findGame(slug: string) {
  return games.find((game) => game.slug === slug);
}
